import '../../models/order_detail_model.dart';
import '../../models/order_model.dart';
import '../enums/order_status_type.dart';

class OrderDummyData {
  static final orders = [
    OrderModel(
      orderid: 1,
      partner: 'GrabFood',
      totalItem: 3,
      note: '',
      status: OrderStatusType.preparing,
      paymentMethod: 'Tiền mặt',
      customerName: 'Thái Quốc Toàn',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 100000,
      discount: 20000,
      finalTotal: 80000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
        OrderDetailModel(
          productId: 3,
          productName: 'Chocolate Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
    OrderModel(
      orderid: 2,
      partner: 'ShopeeFood',
      totalItem: 2,
      note: '',
      status: OrderStatusType.preparing,
      paymentMethod: 'Momo',
      customerName: 'Lê Xuân Bách',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 120000,
      discount: 15000,
      finalTotal: 105000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
    OrderModel(
      orderid: 3,
      partner: 'Beamin',
      totalItem: 2,
      note: '',
      status: OrderStatusType.ready,
      paymentMethod: 'Tiền mặt',
      customerName: 'Võ Vỹ Khang',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 150000,
      discount: 25000,
      finalTotal: 125000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
    OrderModel(
      orderid: 4,
      partner: 'GrabFood',
      totalItem: 2,
      note: '',
      status: OrderStatusType.ready,
      paymentMethod: 'Tiền mặt',
      customerName: 'Thái Quốc Toàn',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 100000,
      discount: 20000,
      finalTotal: 80000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
    OrderModel(
      orderid: 5,
      partner: 'GrabFood',
      totalItem: 2,
      note: '',
      status: OrderStatusType.delivered,
      paymentMethod: 'Tiền mặt',
      customerName: 'Thái Quốc Toàn',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 100000,
      discount: 20000,
      finalTotal: 80000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
    OrderModel(
      orderid: 6,
      partner: 'GrabFood',
      totalItem: 2,
      note: '',
      status: OrderStatusType.delivering,
      paymentMethod: 'Tiền mặt',
      customerName: 'Thái Quốc Toàn',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 100000,
      discount: 20000,
      finalTotal: 80000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
    OrderModel(
      orderid: 7,
      partner: 'GrabFood',
      totalItem: 2,
      note: '',
      status: OrderStatusType.cancelled,
      paymentMethod: 'Tiền mặt',
      customerName: 'Thái Quốc Toàn',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 100000,
      discount: 20000,
      finalTotal: 80000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
    OrderModel(
      orderid: 8,
      partner: 'GrabFood',
      totalItem: 2,
      note: '',
      status: OrderStatusType.cancelled,
      paymentMethod: 'Tiền mặt',
      customerName: 'Thái Quốc Toàn',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 100000,
      discount: 20000,
      finalTotal: 80000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
    OrderModel(
      orderid: 9,
      partner: 'GrabFood',
      totalItem: 2,
      note: '',
      status: OrderStatusType.cancelled,
      paymentMethod: 'Tiền mặt',
      customerName: 'Thái Quốc Toàn',
      customerPhone: '0987654321',
      customerAddress: 'Bình phước adcdefgh',
      subtotal: 100000,
      discount: 20000,
      finalTotal: 80000,
      orderDetails: [
        OrderDetailModel(
          productId: 1,
          productName: 'Espresso Sữa Size M',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 40000,
        ),
        OrderDetailModel(
          productId: 2,
          productName: 'Pink Lady Size L',
          extra: ['Ít đường', 'Nhiều topping'],
          note: 'Shop cho em xin 5 quả trứng',
          quantity: 1,
          totalPrice: 60000,
        ),
      ],
    ),
  ];
}
